services:
  nginx:
    container_name: nginx
    image: nginx:latest
    working_dir: /var/www/
    ports:
      - "43000:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - dp-tech-net
    depends_on:
      - phpfpm

  phpfpm:
    container_name: phpfpm
    build:
      context: ./docker/phpfpm
    volumes:
      - ./src:/var/www
    networks:
      - dp-tech-net
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dp-tech
      MYSQL_USER: rabbit
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dp-tech-net

volumes:
  db_data:

networks:
  dp-tech-net:
    driver: bridge
